/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#6C63FF",
        "primary-container": "#675DF9",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#e3dfff",
        "primary-fixed-dim": "#c4c0ff",
        "on-primary-fixed": "#100069",
        "on-primary-fixed-variant": "#3622ca",
        secondary: "#5846c8",
        "secondary-container": "#7161e3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e4dffe",
        "secondary-fixed-dim": "#c7bfff",
        "on-secondary-fixed": "#170065",
        "on-secondary-fixed-variant": "#422db2",
        tertiary: "#7f5300",
        "tertiary-container": "#a06900",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffddb3",
        "tertiary-fixed-dim": "#ffb951",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#633f00",
        surface: "#fcf8ff",
        "surface-bright": "#fcf8ff",
        "surface-dim": "#dbd6f5",
        "surface-variant": "#e4dffe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f1ff",
        "surface-container": "#f0ebff",
        "surface-container-high": "#eae5ff",
        "surface-container-highest": "#e4dffe",
        "on-surface": "#1b192f",
        "on-surface-variant": "#464555",
        "inverse-surface": "#302e45",
        "inverse-on-surface": "#f3eeff",
        "inverse-primary": "#c4c0ff",
        outline: "#777587",
        "outline-variant": "#c7c4d8",
        success: "#55C595",
        "success-container": "#E8F8F0",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: "1rem",
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px'
      }
    },
  },
  plugins: [],
}
